SportsStore/Controllers/CartController.cs
using SportsStore.Model.Abstract;
using SportsStore.Model.Entities;
using SportsStore.Models;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        private readonly IOrderProcessor _orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            _repository = repo;
            _orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста");
            }

            if (ModelState.IsValid)
            {
                _orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();

                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public Product FindSize(Product product, string size)
        {
            foreach (var find in product.SizeMass)
            {
                if (find == size)
                {
                    return product;
                }
            }

            return null;
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl, string size)
        {      
            Product product = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (FindSize(product,size) != null)
            {
                cart.AddItem(product, 1, size);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/Controllers/NavController.cs
using SportsStore.Model.Abstract;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class NavController : Controller
    {
        private readonly IProductRepository _repository;

        public NavController(IProductRepository repo)
        {
            _repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

SportsStore/Controllers/ProductController.cs
using Ninject;
using SportsStore.Model.Abstract;
using SportsStore.Model.Entities;
using SportsStore.Models;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IKernel _ninjectKernel;
        private readonly int _pageSize = 6;
        private readonly IProductRepository _repository;

        public ProductController(IProductRepository productRepository)
        {
            _repository = productRepository;
        }

        public ViewResult List(string search, string category, int page = 1)
        {
            ViewBag.ValueSearch = search;   
            
            ProductsListViewModel model = new ProductsListViewModel
            { 
                Products = _repository.Products
                .Where(p => category == null || p.Category == category)
                .Where(p=> search == null || p.Name.Contains(search) || p.Category.Contains(search))
                .OrderBy(p => p.ProductID).Skip((page - 1) * _pageSize)
                .Take(_pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = _pageSize,
                    TotalItems = _repository.Products
                    .Where(p => category == null || p.Category == category)
                    .Where(p => search == null || p.Name.Contains(search) || p.Category.Contains(search))
                    .Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ViewResult ProductView(int id = 1)
        {
            Product product = _repository.Products
                .Where(p => p.ProductID == id)
                .FirstOrDefault();   
            
            return View(product);
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model SportsStore.Model.Entities.Product

<div class="u anim" style="--delay: .4s">
    <div class="u-wrapper">
        <div class="u-time">@Model.Firma</div>
        <a href="@Url.Action("ProductView","Product",new { id = @Model.ProductID})">
            @if (Model.ImageData != null)
            {
               string url = String.Format("data:{0};base64,{1}", Model.ImageMimeType, Convert.ToBase64String(Model.ImageData, 0, Model.ImageData.Length));
              <img class="img-card" src="@url" />
            }
        </a>
    </div>
    <div class="u-by">@Model.Category</div>
    <div class="u-name">@Model.Name</div>
    <div class="u-view">
        <div class="all-size">
            @{
                foreach (var size in Model.SizeMass)
                {
                    <button id="@size.ToString()@Model.ProductID" class="size" onclick="isActive('@size.ToString()','@Model.ProductID')">@size.ToString()</button>
                }
            }
        </div>
        <a class="sidebar-link"
           href="@Url.Action("ProductView","Product",new { id = @Model.ProductID})">
        </a>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            @Html.HiddenFor(x => x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <p>@Model.Price.ToString("c")</p>
            <input type="submit" style="width: 100%;justify-content: center;" class="vid__button" value="В корзину" />
            <input id="@Model.ProductID" name="size" class="_size" style="visibility:hidden" value="" />
        }
    </div>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/admin.css" rel="stylesheet" type="text/css" />
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/swiper.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <link href="~/Content/humanoid.css" rel="stylesheet" />
    <script>
        function isActive(size, product) {
            console.log(size);
            $(".size").removeClass("is-active-size");//чистим активне кнопки
            $("#" + size + product).addClass("is-active-size");//активация кнопки
            $("._size").val('');//Очистка inputов
            $("#" + product).val(size);//установка выбранного размера
        }
    </script>

</head>
<body>
    <div class="container">
        <div class="sidebar">
            <span class="logo">S</span>
            <a class="logo-expand" href="#">SPORTS STORE</a>
            @{ Html.RenderAction("Menu", "Nav"); }
        </div>
        <div class="wrapper">
            <div class="header">
                    @using (Html.BeginForm("List", "Product",null, FormMethod.Post, new { @class = "search-bar" }))
                    {
                        <input type="text" name="search" placeholder="Поиск товара" value="@ViewBag.ValueSearch">
                    }              
                    <div class="q-settings">
                        @{Html.RenderAction("Summary", "Cart");}
                    </div>
                </div>
            <div class="main-container">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/Scripts/scripts.js"></script>
</body>
</html>