SportsStore/Controllers/AdminController.cs
using SportsStore.Model.Abstract;
using SportsStore.Model.Entities;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IProductRepository _repository;

        public AdminController(IProductRepository repo)
        {
            _repository = repo;
        }

        public ViewResult Index()
        {
            return View(_repository.Products);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageData = new byte[image.ContentLength];
                    product.ImageMimeType = image.ContentType;

                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }

                _repository.AddProduct(product);

                TempData["message"] = string.Format("{0} добавлен", product.Name);

                return RedirectToAction("Index");
            }
            else return View(product);
        }

        public ViewResult Edit(int productId)
        {
            Product product = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageData = new byte[image.ContentLength];
                    product.ImageMimeType = image.ContentType;

                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }

                _repository.SaveProduct(product);

                TempData["message"] = string.Format("{0} сохранен", product.Name);

                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deletedProduct = _repository.DeleteProduct(productId);

            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} удален", deletedProduct.Name);
            }

            return RedirectToAction("Index");
        }
    }
}

SportsStore/Controllers/ProductController.cs
using Ninject;
using SportsStore.Model.Abstract;
using SportsStore.Model.Entities;
using SportsStore.Models;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IKernel _ninjectKernel;
        private readonly int _pageSize = 6;
        private readonly IProductRepository _repository;

        public ProductController(IProductRepository productRepository)
        {
            _repository = productRepository;
        }

        public ViewResult List(string search, string category, int page = 1)
        {
            ViewBag.ValueSearch = search;   
            
            ProductsListViewModel model = new ProductsListViewModel
            { 
                Products = _repository.Products
                .Where(p => category == null || p.Category == category)
                .Where(p=> search == null || p.Name.Contains(search) || p.Category.Contains(search))
                .OrderBy(p => p.ProductID).Skip((page - 1) * _pageSize)
                .Take(_pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = _pageSize,
                    TotalItems = _repository.Products
                    .Where(p => category == null || p.Category == category)
                    .Where(p => search == null || p.Name.Contains(search) || p.Category.Contains(search))
                    .Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = _repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ViewResult ProductView(int id = 1)
        {
            Product product = _repository.Products
                .Where(p => p.ProductID == id)
                .FirstOrDefault();   
            
            return View(product);
        }
    }
}

SportsStore/Views/Admin/Create.cshtml
@model SportsStore.Model.Entities.Product

@{
    ViewBag.Title = "Добавление";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageMimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageMimeType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageMimeType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            Upload new image:
            <input type="file" id="image" name="image" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SportsStore/Views/Admin/Edit.cshtml
@model SportsStore.Model.Entities.Product

@{
    ViewBag.Title = "Админ: Редактирвоание " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Редактирвоание @Model.Name</h1>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.EditorForModel()

    <div class="editor-label">Image</div>
    <div class="editor-field">
        @if (Model.ImageData == null)
        {
            @:None
        }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImage", "Product", new {Model.ProductID })" />
        }
        <div>
            Upload new image:
            <input type="file" name="Image" />
        </div>
    </div>
    <input type="submit" value="Сохранить" />

    @Html.ActionLink("Отменить и вернуться ко списку", "Index")
}

SportsStore/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Model.Entities.Product>

@{
    ViewBag.Title = "Админ: Все товары";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Все товары</h1>
<table class="Grid">
    <tr>
        <th>ID</th>
        <th>Наименование</th>
        <th>Описание</th>
        <th>Размеры</th>
        <th>Фирма</th>
        <th>Категория</th>
        <th class="NumericCol">Стоимость</th>
        <th>Действие</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ProductID</td>
            <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
            <td>@item.Size</td>
            <td class="desc">@item.Description</td>
            <td>@item.Firma</td>
            <td>@item.Category</td>
            <td class="NumericCol">@item.Price.ToString("c")</td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("ProductID", item.ProductID)
                    <input type="submit" value="Удалить" />
                }
            </td>
        </tr>
    }
</table>
<p>@Html.ActionLink("Добавить товар", "Create")</p>